#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
// #define MK_KINETIC_SPEED
#define MK_3_SPEED
#define MK_C_OFFSET_UNMOD 16
#define MK_C_INTERVAL_UNMOD 16
#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 16
#define MK_C_OFFSET_1 16
#define MK_C_INTERVAL_1 16
#define MK_C_OFFSET_2 3
#define MK_C_INTERVAL_2 16
#define MK_W_OFFSET_UNMOD 1
#define MK_W_INTERVAL_UNMOD 40
#define MK_W_OFFSET_0 1
#define MK_W_INTERVAL_0 80
#define MK_W_OFFSET_1 1
#define MK_W_INTERVAL_1 40
#define MK_W_OFFSET_2 1
#define MK_W_INTERVAL_2 20
